apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-31T12:10:18Z"
  generateName: katafygio-56dfc84769-
  labels:
    app: katafygio
    author: system_serviceaccount_kube-system_replicaset-controller
    chart: katafygio-0.5.1
    heritage: Helm
    operation: CREATE
    pod-template-hash: 56dfc84769
    release: katafygio
  name: katafygio-56dfc84769-kgnqm
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: katafygio-56dfc84769
    uid: 3367d89b-2735-45db-afb0-1da44cac4468
spec:
  containers:
  - args:
    - --local-dir=/var/lib/katafygio/data
    - --healthcheck-port=8080
    - --log-level=info
    - --log-output=stdout
    - --resync-interval=300
    - --exclude-kind=replicasets
    - --exclude-kind=endpoints
    - --exclude-kind=events
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:y8
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: katafygio
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: http
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: tmp
      name: katafygio-data
    - mountPath: /etc/katafygio
      name: config-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zwnbq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 65534
  serviceAccount: katafygio
  serviceAccountName: katafygio
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: katafygio-data
    persistentVolumeClaim:
      claimName: katafygio
  - configMap:
      defaultMode: 420
      name: katafygio-config
    name: config-volume
  - name: kube-api-access-zwnbq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:10:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:10:18Z"
    message: 'containers with unready status: [katafygio]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:10:18Z"
    message: 'containers with unready status: [katafygio]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-01-31T12:10:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c0d5bec2e34c062f2fab809bfc17c67cc310bb931e945e3a096e4edd70ec827b
    image: svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio:y8
    imageID: docker-pullable://svl-artifactory.juniper.net/atom-docker/cn2/sharmag07/katafygio@sha256:651b726f3af6856c6259f25f51f8dcd09c721e6d2087aaa7107c6a0d9efbc1c3
    lastState: {}
    name: katafygio
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-01-31T12:10:41Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.1.14
  podIPs:
  - ip: 10.244.1.14
  qosClass: BestEffort
  startTime: "2024-01-31T12:10:18Z"
